import type { VocabCard } from '../types/german';

/**
 * ============================================================================
 * OFFICIAL CEFR GERMAN VOCABULARY DECK (A1 • A2 • B1 • B2)
 * Aligned with Goethe-Institut Wortlisten & Duale Ausbildung (Fachinformatiker)
 * ============================================================================
 */
export const OFFICIAL_GERMAN_VOCAB: VocabCard[] = [
  /* ========================================================================
     A1: START DEUTSCH 1 (Goethe-Institut Essential Foundation)
     Categories: Daily life, housing, transport, food, appointments, time
     ======================================================================== */
  {
    id: 'voc-a1-01',
    german: 'Termin',
    article: 'der',
    plural: 'die Termine',
    translation: 'appointment, date, schedule',
    exampleSentence: 'Ich habe morgen um 10 Uhr einen wichtigen Termin beim Arzt.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-02',
    german: 'Bahnhof',
    article: 'der',
    plural: 'die Bahnhöfe',
    translation: 'train station',
    exampleSentence: 'Der Zug nach Frankfurt fährt vom Hauptbahnhof ab.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-03',
    german: 'Fahrkarte',
    article: 'die',
    plural: 'die Fahrkarten',
    translation: 'ticket (transport)',
    exampleSentence: 'Wo kann ich eine Fahrkarte nach München kaufen?',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-04',
    german: 'Wohnung',
    article: 'die',
    plural: 'die Wohnungen',
    translation: 'apartment, flat',
    exampleSentence: 'Meine neue Wohnung in Berlin hat zwei helle Zimmer.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-05',
    german: 'Schlüssel',
    article: 'der',
    plural: 'die Schlüssel',
    translation: 'key',
    exampleSentence: 'Hier ist der Schlüssel für Ihr Zimmer.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-06',
    german: 'Rechnung',
    article: 'die',
    plural: 'die Rechnungen',
    translation: 'bill, invoice, receipt',
    exampleSentence: 'Können Sie mir bitte die Rechnung per E-Mail schicken?',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-07',
    german: 'Krankenhaus',
    article: 'das',
    plural: 'die Krankenhäuser',
    translation: 'hospital',
    exampleSentence: 'Das Krankenhaus liegt direkt neben der Universität.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-08',
    german: 'Ausweis',
    article: 'der',
    plural: 'die Ausweise',
    translation: 'identity card, ID, passport',
    exampleSentence: 'Bitte zeigen Sie mir Ihren Reisepass oder Ausweis.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-09',
    german: 'Büro',
    article: 'das',
    plural: 'die Büros',
    translation: 'office',
    exampleSentence: 'Unser Büro öffnet montags bis freitags ab 8:30 Uhr.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-10',
    german: 'Flughafen',
    article: 'der',
    plural: 'die Flughäfen',
    translation: 'airport',
    exampleSentence: 'Wie komme ich am schnellsten zum Flughafen Frankfurt?',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-11',
    german: 'Frühstück',
    article: 'das',
    plural: 'die Frühstücke',
    translation: 'breakfast',
    exampleSentence: 'Das Frühstück wird zwischen 7:00 und 10:00 Uhr serviert.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-12',
    german: 'anrufen',
    article: 'none',
    plural: 'rief an, angerufen',
    translation: 'to call (by phone)',
    exampleSentence: 'Ich rufe Sie heute Nachmittag nach der Schule an.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-13',
    german: 'verstehen',
    article: 'none',
    plural: 'verstand, verstanden',
    translation: 'to understand',
    exampleSentence: 'Entschuldigung, können Sie das bitte wiederholen? Ich verstehe es nicht.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-14',
    german: 'brauchen',
    article: 'none',
    plural: 'brauchte, gebraucht',
    translation: 'to need, require',
    exampleSentence: 'Brauchen Sie Hilfe beim Ausfüllen des Formulars?',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-15',
    german: 'Formular',
    article: 'das',
    plural: 'die Formulare',
    translation: 'form, official document to fill',
    exampleSentence: 'Bitte füllen Sie dieses Formular mit Ihren Daten aus.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-16',
    german: 'Sprache',
    article: 'die',
    plural: 'die Sprachen',
    translation: 'language',
    exampleSentence: 'Welche Sprachen sprechen Sie außer Arabisch und Französisch?',
    level: 'A1',
    category: 'academic',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-17',
    german: 'Uhrzeit',
    article: 'die',
    plural: 'die Uhrzeiten',
    translation: 'time of day, clock time',
    exampleSentence: 'Zu welcher Uhrzeit beginnt die Deutschprüfung?',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-18',
    german: 'Gepäck',
    article: 'das',
    plural: 'none',
    translation: 'luggage, baggage',
    exampleSentence: 'Darf ich mein Handgepäck mit ins Flugzeug nehmen?',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-19',
    german: 'Einladung',
    article: 'die',
    plural: 'die Einladungen',
    translation: 'invitation',
    exampleSentence: 'Herzlichen Dank für die Einladung zur Geburtstagsfeier!',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a1-20',
    german: 'Unterschrift',
    article: 'die',
    plural: 'die Unterschriften',
    translation: 'signature',
    exampleSentence: 'Hier unten fehlt noch Ihre persönliche Unterschrift.',
    level: 'A1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },

  /* ========================================================================
     A2: GOETHE-ZERTIFIKAT A2 (Intermediate Daily & Work Life)
     Categories: Job preparation, contracts, health, meetings, transport
     ======================================================================== */
  {
    id: 'voc-a2-01',
    german: 'Ausbildung',
    article: 'die',
    plural: 'die Ausbildungen',
    translation: 'vocational training, apprenticeship',
    exampleSentence: 'Ich möchte eine duale Ausbildung zum Fachinformatiker in Stuttgart machen.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-02',
    german: 'Bewerbung',
    article: 'die',
    plural: 'die Bewerbungen',
    translation: 'job/internship application',
    exampleSentence: 'Ich habe meine Bewerbung mit Lebenslauf an das deutsche IT-Unternehmen geschickt.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-03',
    german: 'Lebenslauf',
    article: 'der',
    plural: 'die Lebensläufe',
    translation: 'curriculum vitae, resume',
    exampleSentence: 'Ein tabellarischer Lebenslauf gehört zu jeder vollständigen Bewerbung.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-04',
    german: 'Praktikum',
    article: 'das',
    plural: 'die Praktika',
    translation: 'internship, practical placement',
    exampleSentence: 'Im Sommer absolviere ich ein vierwöchiges Praktikum als Webentwickler.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-05',
    german: 'Vorstellungsgespräch',
    article: 'das',
    plural: 'die Vorstellungsgespräche',
    translation: 'job interview',
    exampleSentence: 'Nächste Woche habe ich mein erstes Vorstellungsgespräch per Videokonferenz.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-06',
    german: 'Vertrag',
    article: 'der',
    plural: 'die Verträge',
    translation: 'contract, formal agreement',
    exampleSentence: 'Lesen Sie den Ausbildungsvertrag genau durch, bevor Sie unterschreiben.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-07',
    german: 'Kollege',
    article: 'der',
    plural: 'die Kollegen (fem. Kollegin)',
    translation: 'colleague, coworker',
    exampleSentence: 'Meine deutschen Kollegen im Entwicklungsteam sind sehr hilfsbereit.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-08',
    german: 'Erfahrung',
    article: 'die',
    plural: 'die Erfahrungen',
    translation: 'experience',
    exampleSentence: 'Ich habe bereits erste praktische Erfahrungen mit React und TypeScript gesammelt.',
    level: 'A2',
    category: 'academic',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-09',
    german: 'Gehalt',
    article: 'das',
    plural: 'die Gehälter',
    translation: 'salary, wage',
    exampleSentence: 'Die Ausbildungsvergütung wird am Ende jedes Monats ausgezahlt.',
    level: 'A2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-10',
    german: 'Besprechung',
    article: 'die',
    plural: 'die Besprechungen',
    translation: 'meeting, discussion',
    exampleSentence: 'Um 14 Uhr findet die wöchentliche Besprechung im Konferenzraum statt.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-11',
    german: 'vereinbaren',
    article: 'none',
    plural: 'vereinbarte, vereinbart',
    translation: 'to arrange, agree upon (a date/term)',
    exampleSentence: 'Können wir einen neuen Termin für nächste Woche vereinbaren?',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-12',
    german: 'teilnehmen',
    article: 'none',
    plural: 'nahm teil, teilgenommen',
    translation: 'to participate, take part in (an + Dat.)',
    exampleSentence: 'Ich nehme regelmäßig an einem Deutsch-Intensivkurs teil.',
    level: 'A2',
    category: 'academic',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-13',
    german: 'Überweisung',
    article: 'die',
    plural: 'die Überweisungen',
    translation: 'bank transfer, medical referral',
    exampleSentence: 'Die Miete bezahle ich per monatlicher Banküberweisung.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-14',
    german: 'Verspätung',
    article: 'die',
    plural: 'die Verspätungen',
    translation: 'delay',
    exampleSentence: 'Wegen einer Signalstörung hat die Bahn 20 Minuten Verspätung.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-15',
    german: 'Feierabend',
    article: 'der',
    plural: 'none',
    translation: 'end of the workday, closing time',
    exampleSentence: 'Nach 17 Uhr haben wir Feierabend und gehen zusammen joggen.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-16',
    german: 'Kündigung',
    article: 'die',
    plural: 'die Kündigungen',
    translation: 'cancellation, termination of contract, resignation',
    exampleSentence: 'Die Kündigung der Wohnung muss schriftlich eingereicht werden.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-17',
    german: 'Gesundheit',
    article: 'die',
    plural: 'none',
    translation: 'health, well-being',
    exampleSentence: 'Regelmäßiger Sport und gesunde Ernährung sind wichtig für die Gesundheit.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-18',
    german: 'Zeugnis',
    article: 'das',
    plural: 'die Zeugnisse',
    translation: 'certificate, school report, diploma',
    exampleSentence: 'Für die Bewerbung brauche ich eine beglaubigte Übersetzung meines Bac-Zeugnisses.',
    level: 'A2',
    category: 'academic',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-19',
    german: 'Erlaubnis',
    article: 'die',
    plural: 'die Erlaubnisse',
    translation: 'permission, authorization',
    exampleSentence: 'Haben Sie die Erlaubnis, im Homeoffice zu arbeiten?',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-a2-20',
    german: 'Absender',
    article: 'der',
    plural: 'die Absender',
    translation: 'sender (of letter, email)',
    exampleSentence: 'Schreiben Sie den Absender bitte oben links auf den Briefumschlag.',
    level: 'A2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },

  /* ========================================================================
     B1: GOETHE-ZERTIFIKAT B1 (Gateway to Germany & Professional Independence)
     Categories: IT foundations, career, formal emails, specifications, visa
     ======================================================================== */
  {
    id: 'voc-b1-01',
    german: 'Voraussetzung',
    article: 'die',
    plural: 'die Voraussetzungen',
    translation: 'prerequisite, requirement, condition',
    exampleSentence: 'Gute Deutschkenntnisse auf B1/B2-Niveau sind eine grundlegende Voraussetzung für das Visum.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-02',
    german: 'Anforderung',
    article: 'die',
    plural: 'die Anforderungen',
    translation: 'requirement, specification, demand',
    exampleSentence: 'Die Anforderungen an einen Fachinformatiker für Anwendungsentwicklung sind anspruchsvoll.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-03',
    german: 'Zuverlässigkeit',
    article: 'die',
    plural: 'none',
    translation: 'reliability, dependability',
    exampleSentence: 'Im Berufsleben schätzen deutsche Arbeitgeber Zuverlässigkeit und Pünktlichkeit.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-04',
    german: 'Herausforderung',
    article: 'die',
    plural: 'die Herausforderungen',
    translation: 'challenge',
    exampleSentence: 'Das Lernen einer neuen Programmiersprache ist eine spannende Herausforderung.',
    level: 'B1',
    category: 'academic',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-05',
    german: 'Weiterbildung',
    article: 'die',
    plural: 'die Weiterbildungen',
    translation: 'further education, professional training',
    exampleSentence: 'Das Unternehmen bietet seinen Auszubildenden viele Weiterbildungsmöglichkeiten an.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-06',
    german: 'Fachinformatiker',
    article: 'der',
    plural: 'die Fachinformatiker',
    translation: 'IT specialist, computer science expert',
    exampleSentence: 'Als Fachinformatiker für Anwendungsentwicklung programmiert man Softwarelösungen für Kunden.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-07',
    german: 'Fehlermeldung',
    article: 'die',
    plural: 'die Fehlermeldungen',
    translation: 'error message, bug report',
    exampleSentence: 'Wenn das Programm abstürzt, wird eine Fehlermeldung in der Konsole angezeigt.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-08',
    german: 'Datenbank',
    article: 'die',
    plural: 'die Datenbanken',
    translation: 'database',
    exampleSentence: 'Die Benutzerdaten werden sicher in einer relationalen PostgreSQL-Datenbank gespeichert.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-09',
    german: 'Benutzeroberfläche',
    article: 'die',
    plural: 'die Benutzeroberflächen',
    translation: 'user interface (UI)',
    exampleSentence: 'Eine intuitive Benutzeroberfläche erleichtert die Bedienung der Webanwendung.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-10',
    german: 'beherrschen',
    article: 'none',
    plural: 'beherrschte, beherrscht',
    translation: 'to master, command (a language or skill)',
    exampleSentence: 'Um komplexe Anwendungen zu bauen, muss man JavaScript und TypeScript sicher beherrschen.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-11',
    german: 'lösen',
    article: 'none',
    plural: 'löste, gelöst',
    translation: 'to solve, resolve (problems, bugs, tasks)',
    exampleSentence: 'Gemeinsam im Team konnten wir das schwierige Problem in der Softwarearchitektur lösen.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-12',
    german: 'Aufenthaltsgenehmigung',
    article: 'die',
    plural: 'die Aufenthaltsgenehmigungen',
    translation: 'residence permit',
    exampleSentence: 'Mit dem unterschriebenen Ausbildungsvertrag beantrage ich die Aufenthaltsgenehmigung bei der Botschaft.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-13',
    german: 'Anschreiben',
    article: 'das',
    plural: 'die Anschreiben',
    translation: 'cover letter, letter of motivation',
    exampleSentence: 'Im Anschreiben erkläre ich meine Motivation für den Beruf des Fachinformatikers.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-14',
    german: 'Teamfähigkeit',
    article: 'die',
    plural: 'none',
    translation: 'ability to work in a team',
    exampleSentence: 'Neben Fachwissen sind Teamfähigkeit und Kommunikationsstärke entscheidend.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-15',
    german: 'Selbstständigkeit',
    article: 'die',
    plural: 'none',
    translation: 'independence, self-reliance',
    exampleSentence: 'Der Betrieb erwartet von den Auszubildenden eine hohe Selbstständigkeit bei der Problemlösung.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-16',
    german: 'Arbeitgeber',
    article: 'der',
    plural: 'die Arbeitgeber (fem. Arbeitgeberin)',
    translation: 'employer, company',
    exampleSentence: 'Ein moderner Arbeitgeber fördert flexible Arbeitszeiten und kontinuierliches Lernen.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-17',
    german: 'Berufsschule',
    article: 'die',
    plural: 'die Berufsschulen',
    translation: 'vocational school (in dual training)',
    exampleSentence: 'In der dualen Ausbildung verbringt man zwei Tage pro Woche in der Berufsschule.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-18',
    german: 'überzeugen',
    article: 'none',
    plural: 'überzeugte, überzeugt',
    translation: 'to convince, persuade',
    exampleSentence: 'Im Bewerbungsgespräch konnte er die Geschäftsführung mit seinen Projekten überzeugen.',
    level: 'B1',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-19',
    german: 'Sicherheit',
    article: 'die',
    plural: 'die Sicherheiten',
    translation: 'security, safety',
    exampleSentence: 'Die Sicherheit von Passwörtern und Daten hat oberste Priorität in unserem IT-System.',
    level: 'B1',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b1-20',
    german: 'Verhandlung',
    article: 'die',
    plural: 'die Verhandlungen',
    translation: 'negotiation',
    exampleSentence: 'Die Verhandlungen über die Vertragsbedingungen verliefen sehr erfolgreich.',
    level: 'B1',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },

  /* ========================================================================
     B2: GOETHE-ZERTIFIKAT B2 (Professional German & Technical Specialization)
     Categories: Software engineering, business administration, collocations
     ======================================================================== */
  {
    id: 'voc-b2-01',
    german: 'Schnittstelle',
    article: 'die',
    plural: 'die Schnittstellen',
    translation: 'interface, API (Application Programming Interface)',
    exampleSentence: 'Das Frontend kommuniziert über eine abgesicherte REST-Schnittstelle mit dem Server.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-02',
    german: 'Inbetriebnahme',
    article: 'die',
    plural: 'die Inbetriebnahmen',
    translation: 'commissioning, deployment, going live',
    exampleSentence: 'Nach erfolgreichen Integrationstests erfolgte die reibungslose Inbetriebnahme des Servers.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-03',
    german: 'Fehlerbehebung',
    article: 'die',
    plural: 'die Fehlerbehebungen',
    translation: 'debugging, troubleshooting, bug fixing',
    exampleSentence: 'Für die effiziente Fehlerbehebung nutzen Softwareentwickler moderne Debugging-Tools.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-04',
    german: 'Quellcode',
    article: 'der',
    plural: 'die Quellcodes',
    translation: 'source code',
    exampleSentence: 'Der gesamte Quellcode wird im Git-Repository versioniert und durch Code-Reviews geprüft.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-05',
    german: 'Versionsverwaltung',
    article: 'die',
    plural: 'none',
    translation: 'version control system (VCS)',
    exampleSentence: 'Die professionelle Versionsverwaltung mit Git gehört zu den Grundkenntnissen jedes Programmierers.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-06',
    german: 'Qualitätssicherung',
    article: 'die',
    plural: 'none',
    translation: 'quality assurance (QA)',
    exampleSentence: 'Automatisierte Unit-Tests sind ein zentraler Bestandteil der Software-Qualitätssicherung.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-07',
    german: 'Leistungsfähigkeit',
    article: 'die',
    plural: 'none',
    translation: 'performance, capability, efficiency',
    exampleSentence: 'Durch Code-Optimierung konnte die Leistungsfähigkeit der Applikation verdoppelt werden.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-08',
    german: 'zur Verfügung stehen',
    article: 'none',
    plural: 'stand, gestanden',
    translation: 'to be available, at one\'s disposal (collocation)',
    exampleSentence: 'Die neue API-Dokumentation steht allen Entwicklern online zur Verfügung.',
    level: 'B2',
    category: 'grammar',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-09',
    german: 'eine Entscheidung treffen',
    article: 'none',
    plural: 'traf, getroffen',
    translation: 'to make a decision (collocation)',
    exampleSentence: 'Das Architektur-Team muss heute eine wichtige Entscheidung bezüglich des Frameworks treffen.',
    level: 'B2',
    category: 'grammar',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-10',
    german: 'in Betracht ziehen',
    article: 'none',
    plural: 'zog, gezogen',
    translation: 'to take into consideration, consider (collocation)',
    exampleSentence: 'Wir sollten verschiedene Cloud-Anbieter für das Hosting in Betracht ziehen.',
    level: 'B2',
    category: 'grammar',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-11',
    german: 'Datenschutz-Grundverordnung',
    article: 'die',
    plural: 'die DSGVO',
    translation: 'General Data Protection Regulation (GDPR)',
    exampleSentence: 'Jede Webanwendung in Deutschland muss den Vorgaben der Datenschutz-Grundverordnung entsprechen.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-12',
    german: 'Wartung',
    article: 'die',
    plural: 'die Wartungen',
    translation: 'maintenance, servicing',
    exampleSentence: 'Die regelmäßige Wartung der Datenbanken verhindert unerwartete Serverausfälle.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-13',
    german: 'Ausbildungsbetrieb',
    article: 'der',
    plural: 'die Ausbildungsbetriebe',
    translation: 'training company, host employer for apprenticeship',
    exampleSentence: 'Der Ausbildungsbetrieb stellt dem Auszubildenden einen Laptop und alle Arbeitsmittel.',
    level: 'B2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-14',
    german: 'Vergütung',
    article: 'die',
    plural: 'die Vergütungen',
    translation: 'remuneration, apprenticeship allowance/stipend',
    exampleSentence: 'Die Ausbildungsvergütung steigt in Deutschland mit jedem Ausbildungsjahr an.',
    level: 'B2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-15',
    german: 'Kundenanforderung',
    article: 'die',
    plural: 'die Kundenanforderungen',
    translation: 'client / customer requirement',
    exampleSentence: 'In agilen Sprint-Meetings analysieren wir die Kundenanforderungen im Detail.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-16',
    german: 'Skalierbarkeit',
    article: 'die',
    plural: 'none',
    translation: 'scalability',
    exampleSentence: 'Die Microservice-Architektur garantiert die Skalierbarkeit bei Millionen gleichzeitigen Anfragen.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-17',
    german: 'Zertifizierung',
    article: 'die',
    plural: 'die Zertifizierungen',
    translation: 'certification, professional credential',
    exampleSentence: 'Ein Goethe B2-Zertifikat erhöht die Chancen auf einen Ausbildungsvertrag enorm.',
    level: 'B2',
    category: 'academic',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-18',
    german: 'Vereinbarkeit',
    article: 'die',
    plural: 'none',
    translation: 'compatibility, reconciliation (e.g. work-life balance)',
    exampleSentence: 'Das Unternehmen legt großen Wert auf die Vereinbarkeit von Beruf und Weiterbildung.',
    level: 'B2',
    category: 'daily',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-19',
    german: 'Bereitstellung',
    article: 'die',
    plural: 'die Bereitstellungen',
    translation: 'provision, deployment, provisioning',
    exampleSentence: 'Die automatisierte Bereitstellung der Software erfolgt über eine CI/CD-Pipeline.',
    level: 'B2',
    category: 'tech',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'voc-b2-20',
    german: 'Zuverlässig',
    article: 'none',
    plural: 'zuverlässiger, am zuverlässigsten',
    translation: 'reliable, dependable, trustworthy',
    exampleSentence: 'Für den Arbeitgeber ist ein zuverlässiger Auszubildender von unschätzbarem Wert.',
    level: 'B2',
    category: 'ausbildung',
    mastery: 'new',
    timesReviewed: 0,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z'
  }
];
